name: Build on Push

on:
    push:
        branches:
            - master

jobs:
    format-and-build:
        name: Format Repo and Build Theme
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0
                  ref: ${{ github.head_ref }}

            - name: Format Repo
              uses: /scripts/format/push.yml

            - name: Build Theme
              uses: /scripts/build.yml
