name: Build on Push

on:
    push:
        branches:
            - master

jobs:
    format:
        uses: ./.github/workflows/scripts/format/push.yml

    build:
        uses: ./.github/workflows/scripts/build.yml
