name: Format Pull Request

on:
    pull_request:
        branches:
            - master

jobs:
    format:
        name: Format Pull Request
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0
                  ref: ${{ github.head_ref }}

            - name: Format code
              uses: creyD/prettier_action@v4.3
              with:
                  prettier_options: --write .
                  same_commit: true
                  github_token: ${{ secrets.GITHUB_TOKEN }}
