name: Format Pull Request

on: [pull_request]

jobs:
    format:
        name: Setup Linux environment
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0
                  ref: ${{ github.head_ref }}

            - name: Prettify code
              uses: creyD/prettier_action@v4.3
              with:
                  prettier_options: --write .
                  commit_message: "gh-actions: prettify code"
                  github_token: ${{ secrets.GITHUB_TOKEN }}
