name: Lint Pull Request

on: [push]

jobs:
    format:
        name: Lint code
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0
                  ref: ${{ github.head_ref }}

            - name: Install Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 16.x

            - name: Install dependencies
              run: npm ci

            - name: Run eslint
              run: eslint src
