name: Lint Pull Request

on: [push]

jobs:
    format:
        name: Lint code
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0
                  ref: ${{ github.head_ref }}

            - name: Run ESlint
              uses: stefanoeb/eslint-action@1.0.2
              with:
                  files: src/
