name: Format and Lint Pull Request

on:
    pull_request:
        branches:
            - master

jobs:
    format:
        name: Format code
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0
                  ref: ${{ github.head_ref }}

            - name: Prettify code
              uses: creyD/prettier_action@v4.3
              with:
                  prettier_options: --write .
                  only_changed: true
                  commit_message: "gh-actions: format code"
                  github_token: ${{ secrets.GITHUB_TOKEN }}

    lint:
        name: Lint code
        runs-on: ubuntu-latest
        needs: format

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0
                  ref: ${{ github.head_ref }}

            - name: Install Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 16.x

            - name: Install dependencies
              run: npm ci

            - name: Run eslint
              run: npm run lint
